//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace outfit_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public long id_sale { get; set; }
        public System.DateTime date { get; set; }
        public int total { get; set; }
        public long id_reservation { get; set; }
        public long id_seller { get; set; }
    
        public virtual reservation reservation { get; set; }
        public virtual seller seller { get; set; }
    }
}
